// --------------- IMPORTS ---------------
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { getAllAnswersRequest } from "../services/requests/answer";


// --------------- MIDDLEWARES ---------------
const getAllAnswers = createAsyncThunk("root/fetchAnswers", async () => {
    try {
        // console.log("making request ...");
        const answers = await getAllAnswersRequest();
        // console.log("finished");
        return answers;
    } catch (error) {
        throw error;
    };
});


// --------------- REDUCER ---------------
// INTERFACE:
interface AnswerAttributes {
    answer_id: number;
    full_name: string;
    phone_number: string;
    start_date: string;
    preferred_language: string;
    how_found: string;
    newsletter_subscription: boolean | null;
};

interface answerState {
    session_id: string;
    answers: {
        data: AnswerAttributes[] | null,
        isSuccessful: Boolean,
        isRejected: Boolean,
        isLoading: Boolean
    },
};

const initialState: answerState = {
    session_id: "",
    answers: {
        data: null,
        isSuccessful: false,
        isRejected: false,
        isLoading: false
    }
};

const rootReducer = createSlice({
    name: "root",
    initialState,
    reducers: {
        setSessionId: (state, action) => {
            // The payload is the session_id generated by the postAnswer controller.
            state.session_id = action.payload
        }
    },
    extraReducers: (builder) => {
        builder
            .addCase(getAllAnswers.pending, (state) => {
                state.answers.isLoading = true;
                state.answers.isRejected = false;
                state.answers.isSuccessful = false;
                state.answers.data = null
            })
            .addCase(getAllAnswers.rejected, (state) => {
                state.answers.isLoading = false;
                state.answers.isRejected = true;
                state.answers.isSuccessful = false;
                state.answers.data = null
            })
            .addCase(getAllAnswers.fulfilled, (state, action) => {
                state.answers.isLoading = false;
                state.answers.isRejected = false;
                state.answers.isSuccessful = true;
                state.answers.data = action.payload
            })
    }
});


// --------------- EXPORTS ---------------
export {
    getAllAnswers,
};
export const { setSessionId } = rootReducer.actions;
export default rootReducer.reducer;